hogwarts_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from hogwarts_inventory.forms import UserLoginForm
from hogwarts_inventory.models import User, db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST' ])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)



            user = User(email,password = password)
            db.session.add(user)
            db.session.commit()


            flash(f"You have succesfully created a user account{email}", 'user-created')
            return redirect(url_for('auth.signin'))


    except:
        raise Exception('Invalid Form Data: Please check your email')

    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ["GET", 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect.', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception("Invalid Form Data or User Does not Exist: Check sign up")

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

hogwarts_inventory/site/routes.py
from flask import Blueprint, render_template


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

hogwarts_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>

    <nav class="ct-nav">
        <div>
            <img src="../static/images/images1.jpg" alt="Hogwarts">
        </div>
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home')}}">
                    <li> Hogwarts </li>
                </a>
                <a href="{{ url_for('site.profile')}}">
                    <li>Profile</li>
                </a>
                <a href="https://www.wizardingworld.com/collections/first-year-challenges">
                    <li>Challenges</li>
                </a>
                <a href="{{ url_for('auth.signin')}}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup')}}">
                    <li>Sign Up</li>
                </a>
                <a href="{{ ('/logout')}}">
                    <li>Sign out</li>
                </a>
            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

hogwarts_inventory/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <feildset id="email-field">
            {{ form.email.label}}

            {{form.email(class = "form-control" , placeholder = "Enter email here.")}}
        </feildset>
        <feildset id="pass-field">
            {{ form.password.label}}
            {{ form.password(class = "form-control", placeholder = "Enter password here")}}
        </feildset>

        
         {{ form.submit_button(class="btn btn-primary btn-block") }}

    </div>


</form>